server:
  port: 2333
  address: 127.0.0.1

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "CHANGE-ME-any-password-you-like"
    sources:
      youtube: false

plugins:
  youtube:
    enabled: true
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
    spotify:
      clientId: "YOUR-SPOTIFY-CLIENT-ID"
      clientSecret: "YOUR-SPOTIFY-CLIENT-SECRET"
      countryCode: "CA"
